---
version: "2.0"

services:
  db:
    image: postgres:11.6-alpine
    env:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=rootadmin
      - POSTGRES_DB=codimd
    expose:
      - port: 5432
        as: 5432
        to:
          - service: db
    ready-cmd:
      - "psql"
      - "-w"
      - "-U"
      - "codimd"
      - "-d"
      - "codimd"
      - "-c"
      - "SELECT 1"
  codimd:
    image: hackmdio/hackmd:2.4.1
    env:
      - CMD_DB_URL=postgres://codimd:rootadmin@127.0.0.1:5432/codimd
      - CMD_USECDN=false
    depends-on:
      - db
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true

deployment:
  db:
    lagrange:
      profile: db
      count: 1
  codimd:
    akash:
      profile: codimd
      count: 1